services:
  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: donaton_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  eureka-server:
    build:
      context: ./donaton-backend/eureka-server
    ports:
      - "8761:8761"

  donation-service:
    build:
      context: ./donaton-backend/donation-service
    ports:
      - "8082:8082"
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/donaton_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  logistics-service:
    build:
      context: ./donaton-backend/logistics-service
    ports:
      - "8083:8083"
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/donaton_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  bff-service:
    build:
      context: ./donaton-backend/bff-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - donation-service
      - logistics-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  frontend:
    build:
      context: ./donaton-frontend
    ports:
      - "3000:3000"

volumes:
  mysql_data:
