version: '3.8'

services:
  # --- BASE DE DATOS MYSQL ---
  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: donaton_db
    volumes:
      - mysql_data:/var/lib/mysql

  # --- EUREKA SERVER ---
  eureka-server:
    build:
      context: ./donaton-backend/eureka-server
    ports:
      - "8761:8761"

  # --- MICROSERVICIOS ---
  donation-service:
    build:
      context: ./donaton-backend/donation-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/donaton_db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  logistics-service:
    build:
      context: ./donaton-backend/logistics-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/donaton_db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # --- BFF ---
  bff-service:
    build:
      context: ./donaton-backend/bff-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - donation-service
      - logistics-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  # --- FRONTEND ---
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./donaton-frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

volumes:
  mysql_data: