server:
  port: 8083

spring:
  application:
    name: logistics-service
  datasource:
    # Usamos variables de entorno con un valor por defecto para desarrollo local
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/donaton_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}