server:
  port: 8080

spring:
  application:
    name: bff-service
  cloud:
    gateway:
      routes:
        - id: donation-service-route
          uri: lb://donation-service
          predicates:
            - Path=/donations/**
        - id: logistics-service-route
          uri: lb://logistics-service
          predicates:
            - Path=/logistics/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/